### ISSUE TITLE
What is tag-machine?

### ISSUE THREAD

**Issue by azulika** [fpgaminer/joytag#13]
Thanks for the great project. I'm planning to train Joytag myself, and referred to https://github.com/fpgaminer/joytag/tree/main/training/fused-dataset , but I'm a bit puzzled about the "tag-machine." I've never heard of it - is it some kind of dataset? Where is it available?

**Comment by fpgaminer** [comment]
JoyTag was trained on the Danbooru2021 dataset plus a small set of manually tagged photorealistic images to extend it into that domain.  "tag-machine" is just a UI/server that was built to facilitate this manual tagging process.  And it was easier to build the "fused" (danbooru + those images) training dataset by querying this server, since everything was in there.

tag-machine itself isn't released, nor is the manually tagged stuff. Danbooru2021 is public though.
